/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#444749",
        "on-surface": "#0b1c30",
        "on-primary-fixed": "#1c0062",
        "surface-container-low": "#eff4ff",
        "primary": "#451ebb",
        "surface": "#f8f9ff",
        "inverse-primary": "#cabeff",
        "on-primary-fixed-variant": "#4723be",
        "surface-variant": "#d3e4fe",
        "primary-container": "#5d3fd3",
        "on-tertiary-fixed": "#191c1e",
        "tertiary-fixed-dim": "#c4c7c9",
        "primary-fixed": "#e6deff",
        "inverse-on-surface": "#eaf1ff",
        "on-error": "#ffffff",
        "tertiary": "#414546",
        "primary-fixed-dim": "#cabeff",
        "surface-container-highest": "#d3e4fe",
        "on-primary-container": "#d8ceff",
        "surface-bright": "#f8f9ff",
        "on-surface-variant": "#484554",
        "secondary": "#565e74",
        "background": "#f8f9ff",
        "on-tertiary": "#ffffff",
        "outline": "#797586",
        "on-secondary-fixed": "#131b2e",
        "surface-dim": "#cbdbf5",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#3f465c",
        "secondary-fixed": "#dae2fd",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#bec6e0",
        "on-background": "#0b1c30",
        "secondary-container": "#dae2fd",
        "outline-variant": "#c9c4d7",
        "on-secondary": "#ffffff",
        "error": "#ba1a1a",
        "on-tertiary-container": "#d2d4d6",
        "inverse-surface": "#213145",
        "tertiary-fixed": "#e0e3e5",
        "tertiary-container": "#595c5e",
        "on-error-container": "#93000a",
        "surface-tint": "#6042d6",
        "surface-container-high": "#dce9ff",
        "surface-container": "#e5eeff",
        "on-secondary-container": "#5c647a"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-desktop": "40px",
        "gutter": "24px",
        "container-max": "1280px",
        "unit-base": "8px",
        "stack-sm": "12px",
        "stack-lg": "48px",
        "margin-mobile": "16px",
        "stack-md": "24px"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        headline: ["Geist", "sans-serif"],
      }
    },
  },
  plugins: [],
}
